package madelinebyrne.gardenapp;

/**
 * Created by Madeline Byrne on 6/17/2016.
 */

public class FIELD
{
    public Integer ID; //autogenerated and unique to every object (used for reference)
    public String fieldName;
    public String fieldContent;

}
