package madelinebyrne.gardenapp;

/**
 * Created by Madeline Byrne on 6/17/2016.
 */

public class GARDEN
{
    public String gardenName; //set by user
    public Integer ID; //autogenerated and unique to every object (used for reference)

    //MAP object
    //TAG objects
}
