package madelinebyrne.gardenapp;

/**
 * Created by Madeline Byrne on 6/17/2016.
 */

public class MAP
{
    public Integer ID; //autogenerated and unique to every object (used for reference)
    //determine GPS or simple image
}
