package madelinebyrne.gardenapp;

/**
 * Created by Madeline Byrne on 6/17/2016.
 */

public class TAG
{
    public Integer ID; //autogenerated and unique to every object (used for reference)
    //FIELD objects
}

