package madelinebyrne.gardenapp;

import android.net.wifi.p2p.WifiP2pManager;

import java.util.ArrayList;
import java.util.List;


/**
 * Created by Madeline Byrne on 6/17/2016.
 */

public class TAG
{
    //location cordinates (gps or image tbd)
    public Integer ID; //autogenerated and unique to every object (used for reference)
    public List fieldsList = new ArrayList() {}; //FIELD objects

    //-------------------------------------METHODS------------------------------------------------

    //create or edit a genus field (add user input) and add to the list of fields
    public void editGenus(String userGenusFieldInput)
    {
      //  if (fieldsList.contains(a))
       // {
            //a.fieldContent=userGenusFieldInput;
       // }
        //else
      //  {
            Object a = new GenusFIELD(userGenusFieldInput);
            fieldsList.add(a);
       // }
    }

    //create a common name field (add user input) and add to the list of fields
    public void createCommonName(String userCommonNameFieldInput)
    {
        //add a common name field and user input
        Object b = new CommonNameFIELD(userCommonNameFieldInput);
        fieldsList.add(b);
    }

    //create a species field (add user input) and add to the list of fields
    public void createSpecies(String userSpeciesFieldInput)
    {
        //add a species field and user input;
        Object c = new SpeciesFIELD(userSpeciesFieldInput);
        fieldsList.add(c);
    }

    //constructor
    public TAG(String userGenusFieldInput, String userCommonNameFieldInput, String userSpeciesFieldInput)
    {
        //generate garden tag ID

        //record tag location

        //initialize with ONE important field (tbd)
    }

}
