package madelinebyrne.gardenapp;

import java.util.Enumeration;
import java.util.function.Function;

/**
 * Created by Madeline Byrne on 6/17/2016.
 */

public class USER
{
    public String username; //set by user on initialization (used for authentication)
    public String password; //set by user on initialization (used for authentication)
    public Integer ID; //autogenerated and unique to every object (used for reference)
    public Enumeration privileges; //used for sharing purposes - ie readonly, write, etc

    //UPDATED LOCATION object

    public Boolean passwordMatch;
    //constructor
    public USER(String usernameInput, String passwordInput1, String passwordInput2)
    {

        this.username = usernameInput;
        if (passwordInput1==passwordInput2)
        {
            this.password=passwordInput1;
            passwordMatch=true;
        }
        else{passwordMatch=false;}//UI logic asks to reenter password
    }
    //login method --??
}





