package madelinebyrne.gardenapp;

import java.util.Enumeration;

/**
 * Created by Madeline Byrne on 6/17/2016.
 */

public class USER
{
    public String username; //set by user on initialization (used for authentication)
    public String password; //set by user on initialization (used for authentication)
    public Integer ID; //autogenerated and unique to every object (used for reference)
    public Enumeration privileges; //used for sharing purposes - ie readonly, write, etc

    //UPDATED LOCATION object
}
